# Generated by Django 2.0 on 2021-07-14 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phoneNumber', models.IntegerField()),
                ('pinCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CovidResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='negative', max_length=20)),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelHistory', models.BooleanField()),
                ('contactWithCovidPatient', models.BooleanField()),
                ('symptoms', models.CharField(max_length=256)),
                ('riskPercentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phoneNumber', models.IntegerField(max_length=10)),
                ('pinCode', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='symptoms',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
        migrations.AddField(
            model_name='covidresult',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
    ]
